services:
  db: # Banco de dados
    image: postgres:17-alpine
    volumes: #TODO fazer o volumes pegar o .sql e rodar
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "rinha"

    deploy:
      resources:
        limits:
          cpus: "0.85"
          memory: "1.7GB"
    networks:
      - private_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api1: # API - Instância 01
    build: .
    image: api
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DB_USER: "postgres"
      DB_PASS: "mysecretpassword"
      DB_HOST: db
      DB_PORT: "5432"
      DB_DBNAME: "rinha"
      API_PORT: "8080"

    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "0.4GB"
    networks:
      - public_network
      - private_network

  api2: # API - Instância 01
    build: .
    image: api
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DB_USER: "postgres"
      DB_PASS: "mysecretpassword"
      DB_HOST: db
      DB_PORT: "5432"
      DB_DBNAME: "rinha"
      API_PORT: "8080"
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "0.4GB"
    networks:
      - public_network
      - private_network

  nginx: # Load Balancer
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    networks:
      - public_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
